stages:

  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        pool:
          name: 'NKMachine'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Use Node.js'
          - script: npm install
            displayName: 'Install Dependencies'
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: $(Build.SourcesDirectory)
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: $(Build.ArtifactStagingDirectory)/functionapp.zip
              replaceExistingArchive: true
            displayName: 'Package Function App'

  - stage: Test
    displayName: 'Test Stage'
    variables:
      - group: build_lock
    jobs:
      - job: Test
        displayName: 'Run Unit Tests'
        pool:
          name: 'NKMachine'  # Ensure this is the correct self-hosted agent pool name
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Use Node.js'
          - script: npm install
            displayName: 'Install Dependencies'
          - script: npm test
            displayName: 'Run Tests with Jest'

  - stage: Deploy
    displayName: 'Deploy Stage'
    jobs:
      - deployment: DeployFunction
        displayName: 'Deploy to Azure Function App'
        environment: production
        pool:
          name: 'NKMachine'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFunctionApp@1
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appName: $(functionAppName)
                    package: $(Build.ArtifactStagingDirectory)/functionapp.zip
                    resourceGroupName: $(resourceGroup)
                    deploymentMethod: 'zipDeploy'
                  displayName: 'Deploy to Azure Function App'