stages:

  - stage: Build
    displayName: 'Build Stage'
    variables:
      - group: build_lock
    jobs:
      - job: Build
        displayName: 'Install Dependencies'
        pool:
          name: 'NKMachine'  # Ensure this is the correct self-hosted agent pool name
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Use Node.js'
          
          - script: npm install
            displayName: 'Install Dependencies'
          
          # - script: npm run build
          #   displayName: 'Build Application'

  - stage: Test
    displayName: 'Test Stage'
    variables:
      - group: build_lock
    jobs:
      - job: Test
        displayName: 'Run Unit Tests'
        pool:
          name: 'NKMachine'  # Ensure this is the correct self-hosted agent pool name
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Use Node.js'
          - script: npm install
            displayName: 'Install Dependencies'
          - script: npm test
            displayName: 'Run Tests with Jest'

  - stage: Deploy
    displayName: 'Deploy Stage'
    variables:
      - group: build_lock
    jobs:
      - deployment: DeployFunction
        displayName: 'Deploy to Azure Function App'
        environment: production
        pool:
          name: 'NKMachine'  # Ensure this is the correct self-hosted agent pool name
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFunctionApp@1
                  inputs:
                    azureSubscription: 'AZFunction'
                    appName: 'HelloFunctionNK'
                    package: '$(Build.ArtifactStagingDirectory)'
