stages:
  
  - stage: Build
    displayName: 'Build Stage'
    lockBehavior: sequential
    variables:
      - group: build_lock
    jobs:
      - job: Build
        displayName: 'Install Dependencies'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Use Node.js'
          
          - script: npm install
            displayName: 'Install Dependencies'
          
          - script: npm run build
            displayName: 'Build Application'

  - stage: Test
    displayName: 'Test Stage'
    lockBehavior: sequential
        variables:
          - group: build_lock
    jobs:
      - job: Test
        displayName: 'Run Unit Tests'
        steps:
          - script: npm test
            displayName: 'Run Tests with Jest'

  - stage: Deploy
    displayName: 'Deploy Stage'
    lockBehavior: sequential
    variables:
      - group: build_lock
    jobs:
      - deployment: DeployFunction
        displayName: 'Deploy to Azure Function App'
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFunctionApp@1
                  inputs:
                    azureSubscription: 'AZFunction'  # Set up in Azure DevOps
                    appName: 'HelloFunction'  # Name of your Azure Function App
                    package: '$(Build.ArtifactStagingDirectory)'  # Path to built files
